### ISSUE TITLE
A pull-stream version

### ISSUE THREAD

**Issue by jamen** [ahdinosaur/cli-prompter#1]
This repo is awesome.  I was pretty much going to create the same thing (with the same object format and all), but for pull-stream at `pull-prompt` instead.  Do you have something like that or plan on making one?

I was thinking something like this:

```js
pull(
  questions(),
  prompt(),
  pull.collect(function (err, answers) {
    // ...
  })
)
```

Then, for example, you could use something like `pull-notify` to easily generate new prompts as they are anwsered, or other cool things using sources dynamically.

**Comment by ahdinosaur** [comment]
@jamen that sounds awesome, definitely keen! :+1:

for context, i went with this approach after playing around [here](https://github.com/ahdinosaur/kindling/blob/v2/index.js) with [`enquirer`](https://github.com/enquirer/enquirer) last night. then tonight i found the ecosystem around [`prompt-skeleton`](https://github.com/derhuerst/prompt-skeleton) and just threw this together, doing a simple callback approach to wrap some of those modules to get the same example working.

i'd be happy to pull in any pull streamy ways of doing prompts, so feel free to pull request or whatevers.  now i should probably sleep. :sleeping:

**Comment by jamen** [comment]
@ahdinosaur Alright fair, I'll see what I can do today then.

I also tried `enquirer` a few days ago, from [`generate`](https://github.com/generate/generate), which is what inspired the pull-stream idea...  Small world.  :p

**Comment by derhuerst** [comment]
@ahdinosaur Author of `prompt-skeleton` here. I'm happy to explore new JS interfaces for prompts, as regular streams seem like an overkill. When I tried out pull streams a while ago, they felt extremely nice to work with.

Also, let me know of any screen & line clearing issues you encounter with any of [the prompts](https://github.com/derhuerst/prompt-skeleton#prompts-using-prompt-skeleton)!

**Comment by jamen** [comment]
I think we can just do:

```js
pull.asyncMap(prompter)
```

**Comment by ahdinosaur** [comment]
hey @jamen, i woke up and had a play: https://github.com/ahdinosaur/cli-prompter/commit/fe80587f66473a5911836714d19374995492a19c. :cat:

i'm wondering how values accumulate in this module, like should future prompts know about all previous answers, and should they be able to even modify previous answers?

**Comment by ahdinosaur** [comment]
thanks @derhuerst, i appreciate your work. yeah node streams are cool, but seems they're being used mostly as an event emitter. the pull streamy way of doing this is [`pull-notify`](https://www.npmjs.com/package/pull-notify), but this buffers every "event" until it's pulled, when for a purely real-time activity like a command-line prompt you may be better served by [an event bus](https://github.com/yoshuawuyts/nanobus) or [observables](https://www.npmjs.com/package/observ).

> Also, let me know of any screen & line clearing issues you encounter with any of the prompts!

well okay, i have noticed in the [example](https://github.com/ahdinosaur/cli-prompter/blob/master/example.js) that the autocomplete prompt clears some of the previous question + answers when doing suggestions. but still really awesome that this all works.

**Comment by jamen** [comment]
@ahdinosaur I think maybe the state could be left up to the user

I recently seen some of @nichoth's stuff.  I pushed an example (https://github.com/ahdinosaur/cli-prompter/commit/d9c6b58ea2831c3c4f1bd49b8543826ff0a632e6) that uses his [`pull-stream-model`](https://github.com/nichoth/pull-stream-model).

**Comment by derhuerst** [comment]
@ahdinosaur Will look into it, thanks!

**Comment by derhuerst** [comment]
Published fixed versions of and `text-prompt` and `mail-prompt`, as these were easy to fix.

**Comment by jamen** [comment]
So I went and created [`pull-prompt`](https://github.com/jamen/pull-prompt) and gave a stateless and stateful example.
